version: "3.9"

services:
  spark-driver:
    # image: igorrunb/spark-driver
    build:
      context: ./spark_driver
    container_name: spark-driver
    volumes:
      - ./spark_driver:/spark-driver
      - ./spark-3.1.3-bin-hadoop3.2:/spark-driver/spark-3.1.3-bin-hadoop3.2
    depends_on:
      - kafka-server
      - spark-master
      - spark-worker-1
      - spark-worker-2
    environment:
      - SPARK_LOCAL_IP=localhost
      - PYSPARK_DRIVER_PYTHON=python3
      - PYSPARK_PYTHON=python3
    networks:
      - pspd-projeto-final

  spark-master:
    image: igorrunb/spark-master
    container_name: spark-master
    ports:
      - '8080:8080'
    volumes:
      - ./spark-3.1.3-bin-hadoop3.2:/spark-master/spark-3.1.3-bin-hadoop3.2
    networks:
      - pspd-projeto-final

  spark-worker-1:
    image: igorrunb/spark-worker
    container_name: spark-worker-1
    volumes:
      - ./spark-3.1.3-bin-hadoop3.2:/spark-worker/spark-3.1.3-bin-hadoop3.2
    environment:
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_MEMORY=1G
      - SPARK_WORKER_CORES=1
    depends_on:
      - spark-master
    ports:
      - '8088:8081'
    networks:
      - pspd-projeto-final

  spark-worker-2:
    image: igorrunb/spark-worker
    container_name: spark-worker-2
    volumes:
      - ./spark-3.1.3-bin-hadoop3.2:/spark-worker/spark-3.1.3-bin-hadoop3.2
    environment:
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_MEMORY=1G
      - SPARK_WORKER_CORES=1
    depends_on:
      - spark-master
    ports:
      - '8089:8081'
    networks:
      - pspd-projeto-final

  random-kafka-publisher:
    image: igorrunb/random-kafka-publisher
    container_name: random-kafka-publisher
    depends_on:
      - kafka-server
    volumes:
      - ./kafka_2.13-3.2.1:/publisher/kafka_2.13-3.2.1
    networks:
      - pspd-projeto-final

  twitter-kafka-publisher:
    build:
      context: ./twitter
    container_name: twitter-kafka-publisher
    depends_on:
      - kafka-server
    volumes:
      # - ./twitter:/twitter
      - ./kafka_2.13-3.2.1:/twitter/kafka_2.13-3.2.1
    networks:
      - pspd-projeto-final

  discord-kafka-publisher:
    build:
      context: ./discord
    container_name: discord-kafka-publisher
    depends_on:
      - kafka-server
    volumes:
      # - ./discord:/discord
      - ./kafka_2.13-3.2.1:/discord/kafka_2.13-3.2.1
    networks:
      - pspd-projeto-final

  kafka-zookeeper:
    image: igorrunb/kafka-zookeeper
    volumes:
      - ./kafka_2.13-3.2.1:/kafka_zookeeper/kafka_2.13-3.2.1
    networks:
      - pspd-projeto-final

  kafka-server:
    image: igorrunb/kafka-server
    depends_on:
      - kafka-zookeeper
    volumes:
      - ./kafka_2.13-3.2.1:/kafka_server/kafka_2.13-3.2.1
    networks:
      - pspd-projeto-final

  elasticsearch:
    image: elasticsearch:8.4.1
    container_name: elasticsearch
    ports:
      - '9200:9200'
      - '9300:9300'
    environment:
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - discovery.type=single-node
      - xpack.security.enabled=false
      - xpack.security.http.ssl.enabled=false
      - xpack.security.transport.ssl.enabled=false
    networks:
      - pspd-projeto-final

  kibana:
    image: kibana:8.4.1
    container_name: kibana
    depends_on:
      - elasticsearch
    ports:
      - '5601:5601'
    environment:
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    networks:
      - pspd-projeto-final

networks:
  pspd-projeto-final:
    external: true
